name: Stress Tests

on:
  pull_request:
    types: [labeled]

jobs:
  test:
    if: ${{ github.event.label.name == 'stress test' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Run test runner
        run: |
          yarn build
          yarn generate-dynamic-stories
          STORY_STORE_V7=true STRESS_TEST=true yarn test-storybook:ci
