name: Tests-extended

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Run test runner (story store v7)
        run: |
          yarn build
          STORY_STORE_V7=true yarn test-storybook:ci

      - name: Run test runner (stories json mode)
        run: |
          yarn build
          yarn test-storybook:ci-json
